---
- hosts: localhost
  connection: local
  vars:
    list1: ['Apple','Banana','Cat', 'Dog']
    deploya_env_long: development
    deploya_env_short: dev
    template_string: 'This packagefile has the long_env set to:"{{deploya_env_long}}" and the short_en to:"{{deploya_env_short}}"'
    programs: 
        - { program: 'wget'}
        - { program: 'top'}
        - { program: 'git'}
    #['program1','wget','top']
    
    #achine:
    #    env:
    #        - { deployment: 'prod', long_depl: 'production'} 
  tasks:
    - name: Create the file package file
      template:
        src: ../templates/install_package_var_file.j2
        dest: /tmp/testar.DETTA 
