# This file sets the deployment variable to the host
---
#- hosts: localhost
#  tasks:  
- name: SET_DEPLOYMENT | Read Machine-Information from machine-info
  command: sed 's/^DEPLOYMENT=//' /etc/machine-info
  args:
    warn: false
  register: depll_read
  changed_when: no

- name: SET_DEPLOYMENT | Set Deployment Variable
  become: true
  become_user: root
  command: hostnamectl set-deployment {{depll}}
  when: depll is defined and not ( depll_read.stdout =='') and ( depll != depll_read.stdout )
